#NetworkCompression ConfigFile
---
model:
  parseID: False
  ID: 0
  arch_file: models/architectures/arch_log.txt
  conv_size: 2
  kernel_size: [[7, 7], [4, 4]]
  num_filter: [48, 250]
  pool_size: [[4, 4], [6, 6]]
  pool_stride: [[4, 4], [2, 2]]
  conv_stride: [1, 1]
  dense_depth: 1
  dense_neurons: [300]
  dropout_factor: [0.25, 0.0]
quantization:
  quant_w_params:
    quant_conv:         [True ,True ,True ,True ,True ,True ,True ]
    quant_dense:        [True ,True ,True ,True ,True ,True ,True ]
    num_bin_filt_conv:  [0    ,1    ,2    ,3    ,4    ,5    ,6    ]
    num_bin_filt_dense: [0    ,1    ,2    ,3    ,4    ,5    ,6    ]
    max_num_bin_filt:   [6    ,6    ,6    ,6    ,6    ,6    ,6    ]
    max_opt_runs:       [1000 ,1000 ,1000 ,1000 ,1000 ,1000 ,1000 ]
    paper_approach:     [False,False,False,False,False,False,False]
    pow_of_two:         [False,False,False,False,False,False,False]
    bin_quant:          [False,True ,True ,True ,True ,True ,True ]
    log_quant:          [True ,False,False,False,False,False,False]
  quant_act_format:     [[3.984375, 0.      , 8.      ], [3.984375, 0.      , 8.      ],[15.9375,  0.    ,  8.    ], [63.75,  0.  ,  8.  ],[ 63.5, -64. ,   8. ]]
dataset: GTSRB48x48
